id: a29dc26d-a05e-493e-8b97-eb9c2d90b763
name: ads-web-gpt
title: Agent for Google Publisher Tags
description: Agent to monitor web applications using GPT
summary: Agent to monitor web applications using GPT.
level: Community
authors:
  - New Relic Labs
keywords:
  - nrlabs
  - nrlabs-data
  - ads
  - tracking
  - GPT
documentation:
  - name: GPT agent Installation Docs
    url: https://github.com/newrelic/tracker-google-publisher-tags-js
    description: Agent to monitor web applications using GPT.
logo: logo.svg
