id: a99b22a5-5666-4096-b239-8f315700fde0
# Name of the quickstart (required)
name: atlassian-jira

# Displayed in the UI (required)
title: Atlassian JIRA

# Long-form description of the quickstart (required)
description: |
  Jira is a proprietary issue tracking product developed by Atlassian that allows bug tracking and agile project management. You can Integrate New Relic with Atlassian Jira(Cloud) and automatically create and update Jira issues.
  
  [Check out our documentation](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#jira) to set up a JIRA notification channel and provide fast and consistent ways for the right personnel to be notified about incidents


# Displayed in search results and recommendations. Summarizes a packs functionality.
summary: |
  Integrate New Relic with Atlassian Jira(Cloud) and automatically create and update Jira issues.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Matan Moser (New Relic)
  - Ismail Azam (New Relic)

# Keywords for filtering / searching criteria in the UI
keywords:
  - JIRA
  - Atlassian
  - notifications
  - AIOps
  - Incident Intelligence
  - Destinations

installPlans:
  - third-party-atlassian-jira

# Content / Design
logo: logo.png
website: https://www.atlassian.com/
