id: c4512294-8f81-4efa-8f28-6c1db28d288c
# Name of the quickstart (required)
name: speedscale

# Displayed in the UI (required)
title: Speedscale

# Long-form description of the quickstart (required)
description: |
  Speedscale lets you capture traffic from one environment and replay elsewhere. Use the traffic replay to validate new code performance and functionality. Track the SRE golden signals of latency, throughput, CPU, memory and error metrics before you deploy. Preview your container or API behavior in your CI pipeline without having to write any scripts. Any necessary backends are provided by Speedscale’s mocking technology, which also uses past traffic to generate proper responses you expect during traffic replay. 
  
  Speedscale Snapshots are subsets of traffic that you would like to replay to test how your new code reacts, similar to test scenarios. Deploying this quickstart adds a Speedscale dashboard to your New Relic account that includes replay success rates, response time and deep links to reports.
  
  Read the integration tutorial for the Speedscale quickstart on [New Relic Explorer Hub](https://discuss.newrelic.com/t/how-to-integrate-with-speedscale/171099).

  If you have questions about this quickstart please contact support@speedscale.com.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Visualize Speedscale traffic replay performance data in New Relic One dashboards to see how new code will perform in production.

# Support level: New Relic | Verified | Community (required)
level: Verified

# Authors of the quickstart (required)
authors:
  - Speedscale Inc.

# Keywords for filtering / searching criteria in the UI
keywords:
  - traffic
  - replay
  - simulate
  - report
  - newrelic partner

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - third-party-speedscale-integration

documentation:
  - name: Speedscale Installation Docs
    url: https://docs.speedscale.com/reference/integrations/new-relic
    description: The only prerequisite is to obtain your New Relic account id and license key.
  - name: New Relic Explorer Hub
    url: https://discuss.newrelic.com/t/how-to-integrate-with-speedscale/171099
    description: Ask questions in the post on New Relic Explorer Hub

# Content / Design
logo: logo.svg
website: https://speedscale.com
