name: Validate quickstarts

on: [push, workflow_dispatch, pull_request]

jobs:
  ensure-schema-compliance:
    name: Ensure schema compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
  
      - name: Install dependencies
        run: cd utils && yarn install

      - name: Validate files
        run: cd utils && yarn validate-quickstarts


  ensure-quickstart-names-ids-are-unique:
    name: Ensure quickstart names and ids are unique
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
  
      - name: Install dependencies
        run: cd utils && yarn install

      - name: Check for unique names and ids
        run: cd utils && yarn check-quickstart-uniqueness

  ensure-commits-are-conventional:
    name: Ensure commits are conventional
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v2

      - name: Check for non-conventional commits
        run: ./utils/conventional-commits.sh

  ensure-images-are-valid:
    name: Ensure images are valid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: cd utils && yarn install

      - name: Validate Images
        run: cd utils && yarn validate-images

  ensure-logos-exist:
    name: Ensure logos exist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: cd utils && yarn install

      - name: Validate Logos
        run: cd utils && yarn validate-logos


  validate-install-plan-ids:
    name: Validate install plan ids
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: cd utils && yarn install

      - name: Validate new files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          cd utils && yarn validate-install-plans $URL
