name: Validate install plans

on: [workflow_dispatch, pull_request]

jobs:
  validate-install-plan-schema:
    name: Validate install plan schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: cd utils && yarn install

      - name: Validate new files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NR_API_URL: 'https://api.newrelic.com/graphql'
          NR_API_TOKEN: ${{ secrets.NR_API_TOKEN }}
        run: 
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          cd utils && yarn validate-install-plans $URL
